SRC_DIR = ../src
SRC_FILES = search_test.c $(SRC_DIR)/search.c $(SRC_DIR)/board.c $(SRC_DIR)/move.c $(SRC_DIR)/evaluate.c $(SRC_DIR)/global_tools.c

search_test: $(SRC_FILES)
	gcc -Wall -O3 $(SRC_FILES) -o search_test
	## gcc -Wall -pg -O0 $(SRC_FILES) -o search_test

